import { useMemo, useState } from "react";
import { useNavigate, useSearchParams } from "react-router";
import { Barcode, CheckCircle2, Minus, Plus, Search, Share2, Trash2 } from "lucide-react";
import { Button, Card, Input, Label, Modal, Select } from "@/components/ui";
import PageHeader from "@/components/common/PageHeader";
import { useApp } from "@/lib/store";
import type { InvoiceItem, PaymentMethod } from "@/types";
import { money, whatsapp } from "@/utils/format";

export default function Billing() {
  const navigate = useNavigate(); const [searchParams] = useSearchParams(); const { customers, products, addInvoice, business } = useApp();
  const [customerId, setCustomerId] = useState(searchParams.get("customer") || customers[0]?.id || ""); const [items, setItems] = useState<InvoiceItem[]>([]); const [productSearch, setProductSearch] = useState(""); const [discount, setDiscount] = useState(0); const [paid, setPaid] = useState(0); const [method, setMethod] = useState<PaymentMethod>("Cash"); const [success, setSuccess] = useState<{id:string;number:string;total:number}|null>(null);
  const customer = customers.find(c => c.id === customerId);
  const subtotal = items.reduce((s,i) => s + i.rate*i.quantity, 0); const tax = items.reduce((s,i) => s + (i.rate*i.quantity-i.discount)*i.tax/100, 0); const total = Math.max(0, subtotal-discount+tax);
  const addItem = (productId: string) => { const p = products.find(x => x.id === productId); if (!p) return; setItems(v => { const existing = v.find(x => x.productId === p.id); return existing ? v.map(x => x.productId === p.id ? {...x,quantity:x.quantity+1,total:(x.quantity+1)*x.rate*(1+x.tax/100)}:x) : [...v,{id:crypto.randomUUID(),productId:p.id,name:p.name,quantity:1,rate:p.sellingPrice,discount:0,tax:p.gst,total:p.sellingPrice*(1+p.gst/100)}]; }); setProductSearch(""); };
  const quantity = (id:string, delta:number) => setItems(v => v.map(i => i.id===id ? {...i,quantity:Math.max(1,i.quantity+delta)}:i));
  const save = () => { if (!customer || !items.length) return; const invoice = addInvoice({ customerId, customerName: customer.name, date: new Date().toISOString(), items, subtotal, discount, tax, total, paid: Math.min(paid,total), balance: Math.max(0,total-paid), status: paid>=total ? "Paid" : paid>0 ? "Partially Paid" : "Unpaid" }); setSuccess({id:invoice.id,number:invoice.number,total:invoice.total}); };
  const filtered = useMemo(() => products.filter(p => p.name.toLowerCase().includes(productSearch.toLowerCase())).slice(0,5), [products,productSearch]);
  return <div>
    <PageHeader title="Create Bill" description="Create a GST invoice in just a few steps." action={<div className="hidden text-right md:block"><p className="text-xs text-slate-400">Invoice number</p><p className="font-semibold">Auto generated</p></div>} />
    <div className="grid gap-6 xl:grid-cols-[1fr_360px]">
      <div className="space-y-6">
        <Card className="p-5 md:p-6"><div className="mb-5 flex items-center gap-3"><span className="grid size-8 place-items-center rounded-full bg-brand-500 text-sm font-bold text-white">1</span><div><h2 className="font-display font-bold">Customer & invoice details</h2><p className="text-xs text-slate-500">Who is this bill for?</p></div></div><div className="grid gap-4 md:grid-cols-2"><div><Label>Customer</Label><Select value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">Walk-in Customer</option>{customers.map(c=><option value={c.id} key={c.id}>{c.name} · {c.phone}</option>)}</Select><button onClick={()=>navigate("/customers?add=1")} className="mt-2 text-sm font-semibold text-brand-600">+ Add new customer</button></div><div><Label>Invoice date</Label><Input type="date" defaultValue={new Date().toISOString().slice(0,10)} /></div></div></Card>
        <Card className="p-5 md:p-6"><div className="mb-5 flex items-center gap-3"><span className="grid size-8 place-items-center rounded-full bg-brand-500 text-sm font-bold text-white">2</span><div><h2 className="font-display font-bold">Add items</h2><p className="text-xs text-slate-500">Search products or select a recent item</p></div></div><div className="relative"><Search className="absolute left-3.5 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><Input className="pl-10 pr-12" placeholder="Search by product name or SKU" value={productSearch} onChange={e=>setProductSearch(e.target.value)} /><Button variant="ghost" className="absolute right-1 top-0.5 size-10 p-0"><Barcode className="size-5" /></Button>{productSearch && <div className="absolute z-20 mt-2 w-full rounded-xl border border-slate-200 bg-white p-2 shadow-xl">{filtered.map(p=><button key={p.id} onClick={()=>addItem(p.id)} className="flex w-full items-center justify-between rounded-lg p-3 text-left hover:bg-slate-50"><span><span className="block text-sm font-semibold">{p.name}</span><span className="text-xs text-slate-400">{p.stock} {p.unit} in stock</span></span><span className="font-bold">{money(p.sellingPrice)}</span></button>)}</div>}</div><div className="mt-3 flex gap-2 overflow-x-auto pb-1">{products.slice(0,4).map(p=><button key={p.id} onClick={()=>addItem(p.id)} className="shrink-0 rounded-xl border border-slate-200 px-3 py-2 text-left text-xs hover:border-brand-500"><span className="block font-semibold">{p.name.split(" ").slice(-2).join(" ")}</span><span className="text-slate-400">{money(p.sellingPrice)}</span></button>)}</div>
          {items.length===0 ? <div className="mt-6 rounded-2xl border-2 border-dashed border-slate-200 py-10 text-center"><Plus className="mx-auto size-7 text-slate-300"/><p className="mt-2 text-sm font-semibold">No items added yet</p><p className="text-xs text-slate-400">Search above to add your first item</p></div> : <div className="mt-6 space-y-3">{items.map(i=><div key={i.id} className="grid gap-3 rounded-2xl border border-slate-200 p-4 sm:grid-cols-[1fr_auto_auto] sm:items-center"><div><p className="font-semibold">{i.name}</p><p className="text-xs text-slate-400">{money(i.rate)} · GST {i.tax}%</p></div><div className="flex items-center rounded-xl border border-slate-200"><Button variant="ghost" className="size-9 p-0" onClick={()=>quantity(i.id,-1)}><Minus className="size-3"/></Button><span className="w-8 text-center text-sm font-bold">{i.quantity}</span><Button variant="ghost" className="size-9 p-0" onClick={()=>quantity(i.id,1)}><Plus className="size-3"/></Button></div><div className="flex items-center justify-between sm:justify-end"><span className="min-w-20 text-right font-display font-bold">{money(i.rate*i.quantity*(1+i.tax/100))}</span><Button variant="ghost" className="ml-2 size-9 p-0 text-red-500" onClick={()=>setItems(v=>v.filter(x=>x.id!==i.id))}><Trash2 className="size-4"/></Button></div></div>)}</div>}
        </Card>
        <Card className="p-5 md:p-6"><div className="mb-5 flex items-center gap-3"><span className="grid size-8 place-items-center rounded-full bg-brand-500 text-sm font-bold text-white">3</span><div><h2 className="font-display font-bold">Payment</h2><p className="text-xs text-slate-500">Record full or partial payment</p></div></div><div className="grid gap-4 md:grid-cols-2"><div><Label>Amount paid</Label><Input type="number" min="0" max={total} value={paid||""} onChange={e=>setPaid(Number(e.target.value))}/><div className="mt-2 flex flex-wrap gap-2">{[500,1000,2000,total].map((v,index)=><Button key={index} variant="secondary" className="min-h-8 px-3 py-1 text-xs" onClick={()=>setPaid(v)}>{index===3?"Full Amount":money(v)}</Button>)}</div></div><div><Label>Payment method</Label><Select value={method} onChange={e=>setMethod(e.target.value as PaymentMethod)}>{["Cash","UPI","Bank Transfer","Card","Other"].map(v=><option key={v}>{v}</option>)}</Select></div></div></Card>
      </div>
      <aside className="hidden xl:block"><Card className="sticky top-24 p-6"><h2 className="font-display text-lg font-bold">Bill summary</h2><p className="mt-1 text-sm text-slate-500">{items.length} {items.length===1?"item":"items"} added</p><div className="mt-6 space-y-3 text-sm"><div className="flex justify-between text-slate-500"><span>Subtotal</span><span>{money(subtotal)}</span></div><div className="flex items-center justify-between text-slate-500"><span>Discount</span><Input className="min-h-8 w-24 text-right" type="number" value={discount||""} placeholder="₹0" onChange={e=>setDiscount(Number(e.target.value))}/></div><div className="flex justify-between text-slate-500"><span>GST</span><span>{money(tax)}</span></div><div className="flex justify-between border-t border-dashed border-slate-200 pt-4 font-display text-xl font-bold"><span>Grand total</span><span>{money(total)}</span></div><div className="flex justify-between text-emerald-600"><span>Amount paid</span><span>{money(paid)}</span></div><div className="flex justify-between rounded-xl bg-amber-50 p-3 font-bold text-amber-800"><span>Balance due</span><span>{money(Math.max(0,total-paid))}</span></div></div><Button className="mt-6 w-full" disabled={!customer||!items.length} onClick={save}>Save & Share <Share2 className="size-4"/></Button><p className="mt-3 text-center text-xs text-slate-400">You can edit the bill after saving</p></Card></aside>
    </div>
    <div className="fixed inset-x-0 bottom-16 z-30 border-t border-slate-200 bg-white p-3 lg:bottom-0 xl:hidden"><div className="mx-auto flex max-w-screen-xl items-center gap-4"><div className="flex-1"><p className="text-xs text-slate-400">Grand Total</p><p className="font-display text-xl font-extrabold">{money(total)}</p></div><Button disabled={!customer||!items.length} onClick={save}>Save & Share</Button></div></div>
    <Modal open={!!success} onClose={()=>setSuccess(null)} title="Bill created successfully"><div className="text-center"><CheckCircle2 className="mx-auto size-14 text-emerald-500"/><p className="mt-4 text-sm text-slate-500">{success?.number}</p><p className="mt-1 font-display text-3xl font-extrabold">{money(success?.total||0)}</p><div className="mt-6 grid gap-2"><Button onClick={()=>whatsapp(`Hello ${customer?.name},\n\nYour invoice ${success?.number} from ${business.name} is ${money(success?.total||0)}.\n\nPaid: ${money(paid)}\nBalance: ${money(Math.max(0,(success?.total||0)-paid))}\n\nThank you for your business.`)}>Share on WhatsApp</Button><Button variant="secondary" onClick={()=>success&&navigate(`/invoices/${success.id}`)}>View Invoice</Button><Button variant="ghost" onClick={()=>{setItems([]);setPaid(0);setSuccess(null)}}>Create New Bill</Button></div></div></Modal>
  </div>;
}
