import { useEffect, useState } from "react";
import { useNavigate, useSearchParams } from "react-router";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Plus, Search, Users } from "lucide-react";
import { Button, Card, Input, Label, Modal, Select } from "@/components/ui";
import PageHeader from "@/components/common/PageHeader";
import { useApp } from "@/lib/store";
import { money, shortDate } from "@/utils/format";

const schema=z.object({name:z.string().min(2,"Enter customer name"),phone:z.string().min(10,"Enter a valid phone number"),city:z.string().min(2,"Enter city")}); type Form=z.infer<typeof schema>;
export default function Customers(){
 const {customers,addCustomer}=useApp(); const navigate=useNavigate(); const [params,setParams]=useSearchParams(); const [open,setOpen]=useState(false); const [query,setQuery]=useState(""); const [filter,setFilter]=useState("All"); const {register,handleSubmit,formState:{errors},reset}=useForm<Form>({resolver:zodResolver(schema)});
 useEffect(()=>{if(params.get("add")==="1")setOpen(true)},[params]); const close=()=>{setOpen(false);setParams({})}; const submit=(data:Form)=>{addCustomer(data);reset();close()}; const filtered=customers.filter(c=>c.name.toLowerCase().includes(query.toLowerCase())&&(filter==="All"||(filter==="With Balance"&&c.outstanding>0)||(filter==="No Balance"&&c.outstanding===0)||(filter==="Overdue"&&c.outstanding>20000)));
 return <div><PageHeader title="Customers" description="Manage customers and track every balance." action={<Button onClick={()=>setOpen(true)}><Plus className="size-4"/> Add Customer</Button>}/><div className="mb-5 flex flex-col gap-3 md:flex-row"><div className="relative flex-1"><Search className="absolute left-3.5 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><Input className="pl-10" placeholder="Search name or phone" value={query} onChange={e=>setQuery(e.target.value)}/></div><Select className="md:w-48" value={filter} onChange={e=>setFilter(e.target.value)}>{["All","With Balance","No Balance","Overdue"].map(v=><option key={v}>{v}</option>)}</Select></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(c=><Card key={c.id} className="cursor-pointer p-5 transition hover:-translate-y-0.5 hover:border-brand-500 hover:shadow-md" ><button className="w-full text-left" onClick={()=>navigate(`/customers/${c.id}`)}><div className="flex items-start justify-between"><div className="flex gap-3"><div className="grid size-11 place-items-center rounded-full bg-brand-50 font-bold text-brand-600">{c.name.split(" ").map(v=>v[0]).slice(0,2).join("")}</div><div><p className="font-bold">{c.name}</p><p className="text-sm text-slate-500">{c.phone}</p></div></div><Users className="size-4 text-slate-300"/></div><div className="mt-5 grid grid-cols-2 border-t border-slate-100 pt-4"><div><p className="text-xs text-slate-400">Outstanding</p><p className={`mt-1 font-display text-lg font-bold ${c.outstanding>0?"text-amber-600":"text-emerald-600"}`}>{money(c.outstanding)}</p></div><div className="text-right"><p className="text-xs text-slate-400">Last activity</p><p className="mt-1 text-sm font-semibold">{shortDate(c.lastTransaction)}</p></div></div></button></Card>)}</div><Modal open={open} onClose={close} title="Add new customer"><form onSubmit={handleSubmit(submit)} className="space-y-4"><div><Label>Customer name</Label><Input {...register("name")} placeholder="e.g. Rahul Patil"/>{errors.name&&<p className="mt-1 text-xs text-red-600">{errors.name.message}</p>}</div><div><Label>Phone number</Label><Input {...register("phone")} placeholder="98765 43210"/>{errors.phone&&<p className="mt-1 text-xs text-red-600">{errors.phone.message}</p>}</div><div><Label>City / address</Label><Input {...register("city")} placeholder="Pune, Maharashtra"/>{errors.city&&<p className="mt-1 text-xs text-red-600">{errors.city.message}</p>}</div><Button type="submit" className="w-full">Add Customer</Button></form></Modal></div>
}
